### ISSUE TITLE
Copy cosmetic ux changes from figma

### ISSUE THREAD

**Issue by quentincaffeino** [cesko-digital/mistoveskole#38]
List of changes from Klára:

Mobil
 - [x] na mobilu změnit box/form Najít vhodnou školu (.sidebar>.box) z padding: 32px; na padding: 48px 24px
 	- obecně na desktopu je levé a pravé účaří celého sidebaru sidebaru je 32px, ale na mobilu celé stránky 24px (na mobilu je tam teď ten padding, co je na desktopu)
 - [x] opravovala jsem já:
 	- na buttonech bez ikony prosím změnit padding na 16,24 a na buttony s ikonou na 16,16,16,24 resp. 16,24,16,16 – je opraveno ve Figmě DS (jde o to, abychom odstranili aspoň na většině deviců to zalomení textu v buttonu)
 - [x] taby
 	- zvětšit padding-bottom na těch tabech – dle Figmy, kde jsem upravila
 	- typografie na tabech

**Comment by mvdegtyar** [comment]
I've fixed padding for a button with text. We don't have buttons with icon so far.
