### ISSUE TITLE
Portrait tablet responsive breakpoint needs using mobile version/optimisation

### ISSUE THREAD

**Issue by klarasch** [cesko-digital/mistoveskole#50]
Currently, the side panel takes more place than map. Not an ideal solution (my bad), but mobile version would be better.

![IMG_0017](https://user-images.githubusercontent.com/17709591/180601413-6931abbd-46e2-4632-94ab-cf370a206945.png)

**Comment by quentincaffeino** [comment]
fixed in https://github.com/cesko-digital/mistoveskole/pull/58
