### ISSUE TITLE
[Minor improvement proposal] Add useful links to other sections of the site to homepage

### ISSUE THREAD

**Issue by klarasch** [cesko-digital/mistoveskole#52]
Since we now have information for parents; per some of the original design proposals: https://www.figma.com/file/u0Ccgxs0lEE7ioGUnlQM3C/Mv%C5%A0-screens?node-id=191%3A768

**Comment by quentincaffeino** [comment]
That would be duplicate links since same links are in menu, isn't that bad?

**Comment by klarasch** [comment]
Partly, but site promoting menu sections through other means isn't necessarily bad (in fact most landing pages work like this when you think about it – you list a few list items and do "More -these items-" with it  –  it's actually good to promote we have the info section like this which could be otherwise "too hidden" especially on mobile.

Especially now, we need to improve the experience by providing more guidance on e.g. how to sign the kid up for school. So until we have something better, we could have just one link on this phrased as "How does the enrolling process work in the Czech Republic work" linking directly to the page we're linking as such in our infosection (should perhaps open in new window so the icon wouldn't be arrow – that's for in-site links – but external link icon) and "More information about Czech schooling system" link underneath to our section with all information.

What do you think about that? :)

**Comment by stefanides** [comment]
Agree. Except "show map" button there should be some extra link "and how to sign for selected school". and until we have better text, this link is better than nothing :)
